<?php
use eftec\minilang\MiniLang;

/**
* This class has the motor and definitions of the Mini Language.
*.
* @package .
* @generated by https://github.com/EFTEC/MiniLang.
* @version 2.20 2021-09-26T20:33:11-03:00.
*/
class BuildMilkClass extends MiniLang {
	public $numCode=10; // num of lines of code 
	public $usingClass=true; // if true then we are using a class (this class) 
	public function whereRun($lineCode=0) {
		switch($lineCode) {
			case 8:
			case 9:
				return true; // nothing to do
			case 0:
				$result=$this->dict['milk']=='0' && $this->dict['gas']>'0';
				break;
			case 1:
				$result=$this->dict['gas']=='0';
				break;
			case 2:
				$result=$this->dict['store_open']==1 && $this->dict['stock_milk']>'0';
				break;
			case 3:
				$result=$this->dict['store_open']=='0' || $this->dict['stock_milk']=='0';
				break;
			case 4:
				$result=$this->dict['money']>=$this->dict['price'];
				break;
			case 5:
				$result=$this->dict['money']<$this->dict['price'];
				break;
			case 6:
				$result=$this->caller->always();
				break;
			case 7:
				$result=$this->caller->always();
				break;
			default:
				$result=false;
				$this->throwError('Line '.$lineCode.' is not defined');
		}
		return $result;
	} // end function WhereRun
	public function setRun($lineCode=0) {
		switch($lineCode) {
			case 0:
			case 1:
			case 2:
			case 3:
			case 5:
			case 6:
			case 7:
				break; // nothing to do
			case 4:
				$this->dict['milk']=1;
				break;
			case 8:
				$this->dict['gas']='0';
				break;
			case 9:
				$this->dict['gas']='0';
				break;
			default:
				$this->throwError('Line '.$lineCode.' is not defined for set');
		}
	} // end function setRun
	public function elseRun($lineCode=0) {
		switch($lineCode) {
			case 0:
			case 1:
			case 2:
			case 3:
			case 4:
			case 5:
			case 6:
			case 7:
			case 8:
			case 9:
				break; // nothing to do
			default:
				$this->throwError('Line '.$lineCode.' is not defined for else');
		}
	} // end function elseRun
	public function initRun($lineCode=0) {
		switch($lineCode) {
			case 0:
			case 1:
			case 2:
			case 3:
			case 4:
			case 5:
			case 6:
			case 7:
			case 8:
			case 9:
				break; // nothing to do
			default:
				$this->throwError('Line '.$lineCode.' is not defined for init');
		}
	} // end function initRun
} // end class
